### ISSUE TITLE
"sms-call-internet-mi-2014-01-01.txt"

### ISSUE THREAD

**Issue by andrekos** [treselle-systems/CDR_analysis_using_K_means_in_Tableau#1]
Hi. Could you please add the file "sms-call-internet-mi-2014-01-01.txt" into the repo? Your R and Tableau analyses are not reproducible without it. Thanks.

**Comment by treselle-systems** [comment]
"sms-call-internet-mi-2014-01-01.zip" file uploaded into repository.
